import type { LearningPacket } from "@/lib/packet-types";

// Dynamic imports, each packet loads only on its own node page.
export const PACKET_REGISTRY: Record<string, () => Promise<{ packet: LearningPacket }>> = {
  "l0-debug-mindset": () => import("./l0-debug-mindset"),
  "l0-editor": () => import("./l0-editor"),
  "l0-git": () => import("./l0-git"),
  "l0-github": () => import("./l0-github"),
  "l0-python-setup": () => import("./l0-python-setup"),
  "l0-terminal": () => import("./l0-terminal"),
  "l1-classes": () => import("./l1-classes"),
  "l1-control-flow": () => import("./l1-control-flow"),
  "l1-data-structures": () => import("./l1-data-structures"),
  "l1-files-errors": () => import("./l1-files-errors"),
  "l1-functions": () => import("./l1-functions"),
  "l1-matplotlib": () => import("./l1-matplotlib"),
  "l1-numpy": () => import("./l1-numpy"),
  "l1-python-basics": () => import("./l1-python-basics"),
  "l1-testing-modules": () => import("./l1-testing-modules"),
  "l1-vectorization-craft": () => import("./l1-vectorization-craft"),
  "l2-algebra": () => import("./l2-algebra"),
  "l2-derivatives": () => import("./l2-derivatives"),
  "l2-eigen-svd": () => import("./l2-eigen-svd"),
  "l2-functions-graphs": () => import("./l2-functions-graphs"),
  "l2-integrals": () => import("./l2-integrals"),
  "l2-linear-maps": () => import("./l2-linear-maps"),
  "l2-matrices": () => import("./l2-matrices"),
  "l2-multivariable": () => import("./l2-multivariable"),
  "l2-optimization": () => import("./l2-optimization"),
  "l2-probability": () => import("./l2-probability"),
  "l2-random-variables": () => import("./l2-random-variables"),
  "l2-stats-mle": () => import("./l2-stats-mle"),
  "l2-trig": () => import("./l2-trig"),
  "l2-vectors": () => import("./l2-vectors"),
  "l3-backprop-theory": () => import("./l3-backprop-theory"),
  "l3-mlp-numpy": () => import("./l3-mlp-numpy"),
  "l4-attention": () => import("./l4-attention"),
  "l4-transformer": () => import("./l4-transformer"),
  "l5-frames-rotations": () => import("./l5-frames-rotations"),
  "l5-jacobians": () => import("./l5-jacobians"),
  "l5-lie-se3": () => import("./l5-lie-se3"),
  "l6-kalman": () => import("./l6-kalman"),
  "l10-mdp": () => import("./l10-mdp"),
  "l10-tabular": () => import("./l10-tabular"),
  "l11-bc-dagger": () => import("./l11-bc-dagger"),
  "l12-vla-anatomy": () => import("./l12-vla-anatomy"),
};
